apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: fridgy
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: "fridgy.rasztabiga.me"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080
