apiVersion: v1
kind: Secret
metadata:
  name: products-postgresql
  namespace: fridgy
  labels:
    app: products-postgresql
type: Opaque
data:
  postgresql-password: MTJiMzgyYzZjY2Y2Zjg0ODY1Y2I1ZDEzMTEyNTkwNmY3OWY5Yjg4YjRlOTY4MWM4YTQyMjJkYTdiYzM5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-postgresql
  namespace: fridgy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-postgresql
  template:
    metadata:
      labels:
        app: products-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:13.2
          env:
            - name: POSTGRES_USER
              value: products
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: products-postgresql
  namespace: fridgy
spec:
  selector:
    app: products-postgresql
  ports:
    - port: 5432
