apiVersion: v1
kind: Service
metadata:
  labels:
    name: keycloak
  name: keycloak
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "9080"
      port: 9080
      targetPort: 9080
    - protocol: TCP
      name: "9443"
      port: 9443
      targetPort: 9443
    - protocol: TCP
      name: "10990"
      port: 10990
      targetPort: 10990
  selector:
    name: keycloak 
